apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/pagamentos
        pathType: Prefix
        backend:
          service:
            name: payment-api-service
            port:
              number: 80
      - path: /api/v1/payment_notification
        pathType: Exact
        backend:
          service:
            name: payment-api-service
            port:
              number: 80