development:
  clients:
    default:
      uri: <%= ENV.fetch("MONGO_URI", "mongodb://mongo:27017/pagamento_service_development") %>
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      uri: <%= ENV.fetch("MONGO_URI", "mongodb://mongo:27017/pagamento_service_test") %>
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      uri: <%= ENV.fetch("MONGO_URI", "mongodb://mongo:27017/pagamento_service_production") %>
  options:
    raise_not_found_error: false
