name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read 
  pull-requests: read

jobs:
  test-and-analyze:
    name: Test and SonarCloud Scan
    runs-on: ubuntu-latest
    
    services:
       mongodb:
         image: mongo:latest
         ports:
           - 27017:27017

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2' 
          bundler-cache: true 

      - name: Lint code with RuboCop
        run: bundle exec rubocop -f github
        continue-on-error: true

      - name: Security Scan with Brakeman
        run: bundle exec brakeman --no-pager
        continue-on-error: true

      - name: Instalar libs do sistema
        run: sudo apt-get install

      - name: Limpar caches e arquivos temporários
        run: |
          rm -rf tmp/cache
          rm -rf tmp/pids
          rm -rf tmp/sockets
          rm -rf coverage

      - name: Rodar Testes (RSpec)
        env:
          RAILS_ENV: test
          MONGO_URI: mongodb://localhost:27017/payment_test
        run: |
          bundle exec rspec

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
        with:
          args: >
            -Dsonar.verbose=true

      - name: SonarCloud Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-deploy-to-k8s:
    name: Build, Push and Deploy to K8s
    runs-on: ubuntu-latest
    needs: test-and-analyze
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    env:
      ECR_REPOSITORY: soat-challenge/payment-service
      AWS_REGION: sa-east-1
      CLUSTER_NAME: soat-cluster-eks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest


      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Deploy Ngrok and Fetch URL
        run: |
          # 1. Sobe o ngrok no cluster
          kubectl apply -f k8s/ngrok.yaml
          
          # 2. Aguarda o ngrok estar pronto
          kubectl wait --for=condition=available --timeout=60s deployment/ngrok-dx
          
          # 3. Executa um comando temporário no cluster para pegar a URL via API do ngrok
          # O script bootstrap_notification_url.sh faz exatamente isso
          NGROK_URL=$(kubectl exec deployment/ngrok-dx -- curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          
          if [ -z "$NGROK_URL" ] || [ "$NGROK_URL" == "null" ]; then
            echo "Erro ao capturar URL do ngrok"
            exit 1
          fi
          
          NOTIFICATION_URL="${NGROK_URL}/api/v1/payment_notification"
          echo "URL Detectada: $NOTIFICATION_URL"
          
          # 4. Cria ou Atualiza o Secret dinamicamente
          kubectl create secret generic payment-dynamic-configs \
            --from-literal=MERCADOPAGO_NOTIFICATION_URL=$NOTIFICATION_URL \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Substitui a imagem nos arquivos yaml pela imagem recém buildada
          sed -i "s|image: .*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" k8s/*.yaml
          
          # Aplica todas as configurações e deployments
          kubectl apply -f k8s/configs.yaml
          kubectl apply -f k8s/ngrok-deployment.yaml
          kubectl apply -f k8s/api-deployment.yaml
          kubectl apply -f k8s/consumer-deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/payment-api
          kubectl rollout status deployment/payment-worker
          kubectl rollout status deployment/payment-consumer

      - name: Sync Master Key to AWS Secrets Manager
        run: |
          SECRET_NAME="soat/order-service/master_key"
          MASTER_KEY=$(cat config/master.key)

          if aws secretsmanager describe-secret --secret-id "$SECRET_NAME" > /dev/null 2>&1; then
            echo "Atualizando chave existente..."
            aws secretsmanager put-secret-value --secret-id "$SECRET_NAME" --secret-string "$MASTER_KEY"
          else
            echo "Criando novo segredo para a Master Key..."
            aws secretsmanager create-secret --name "$SECRET_NAME" --secret-string "$MASTER_KEY" --description "Master Key do Order Service"
          fi