name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read 
  pull-requests: read

jobs:
  test-and-analyze:
    name: Test and SonarCloud Scan
    runs-on: ubuntu-latest
    
    services:
       mongodb:
         image: mongo:latest
         ports:
           - 27017:27017

    steps:
      - name: Checkout do cÃ³digo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2' 
          bundler-cache: true 

      - name: Lint code with RuboCop
        run: bundle exec rubocop -f github
        continue-on-error: true

      - name: Security Scan with Brakeman
        run: bundle exec brakeman --no-pager
        continue-on-error: true

      - name: Instalar libs do sistema
        run: sudo apt-get install

      - name: Limpar caches e arquivos temporÃ¡rios
        run: |
          rm -rf tmp/cache
          rm -rf tmp/pids
          rm -rf tmp/sockets
          rm -rf coverage

      - name: Rodar Testes (RSpec)
        env:
          RAILS_ENV: test
          REDIS_URL: redis://localhost:6379/0
          MONGO_URI: mongodb://localhost:27017/payment_test
        run: |
          bundle exec rspec

      - name: Fix coverage paths for Sonar
        run: |
          ruby -rjson -e '
            file = "coverage/coverage.json"
            data = JSON.parse(File.read(file))
            pwd = Dir.pwd + "/"
            data["coverage"] = data["coverage"].transform_keys { |k| k.start_with?(pwd) ? k.sub(pwd, "") : k }
            File.write(file, JSON.generate(data))
          '

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
        with:
          args: >
            -Dsonar.verbose=true

      - name: SonarCloud Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Publicar Resumo de Cobertura
        if: always()
        run: |
          COVERAGE=$(jq '.metrics.covered_percent' coverage/coverage.json)
          echo "### ðŸ“Š Cobertura de CÃ³digo: ${COVERAGE}%" >> $GITHUB_STEP_SUMMARY
          
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "âŒ Cobertura abaixo de 80%!" >> $GITHUB_STEP_SUMMARY
          else
            echo "âœ… Meta de 80% atingida!" >> $GITHUB_STEP_SUMMARY
          fi

  build-and-deploy-to-ecr:
    name: Build and Deploy to ECR
    runs-on: ubuntu-latest
    needs: test-and-analyze
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    env:
      ECR_REPOSITORY: soat-challenge/payment-service
      AWS_REGION: sa-east-1

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          IMAGE_TAG=${{ github.sha }}
          
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest